# Generated by Django 4.2.21 on 2025-08-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('excerpt', models.TextField(verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('category', models.CharField(choices=[('edital', 'Edital'), ('noticia', 'Notícia'), ('dica', 'Dica'), ('evento', 'Evento')], max_length=20, verbose_name='Categoria')),
                ('date', models.DateField(verbose_name='Data')),
                ('read_time', models.IntegerField(verbose_name='Tempo de Leitura (minutos)')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Fonte')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('urgent', models.BooleanField(default=False, verbose_name='Urgente')),
                ('status', models.CharField(choices=[('published', 'Publicado'), ('draft', 'Rascunho'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='Status')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
