# Generated by Django 4.2.21 on 2025-08-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Link'),
        ),
    ]
