# Generated by Django 4.2.21 on 2025-08-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('bio', models.TextField(verbose_name='Biografia')),
                ('image', models.ImageField(blank=True, null=True, upload_to='professors/', verbose_name='Imagem')),
                ('specialties', models.TextField(verbose_name='Especialidades')),
                ('experience', models.TextField(verbose_name='Experiência')),
                ('approvals_count', models.IntegerField(default=0, verbose_name='Número de Aprovações')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Avaliação')),
                ('achievements', models.TextField(blank=True, verbose_name='Conquistas')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['name'],
            },
        ),
    ]
