# Generated by Django 4.2.21 on 2025-08-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('full_description', models.TextField(verbose_name='Descrição Completa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Original')),
                ('duration', models.CharField(max_length=50, verbose_name='Duração')),
                ('students_count', models.IntegerField(default=0, verbose_name='Número de Alunos')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Avaliação')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Número de Avaliações')),
                ('benefits', models.TextField(verbose_name='Benefícios')),
                ('requirements', models.TextField(verbose_name='Requisitos')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('draft', 'Rascunho')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('themembers_link', models.URLField(blank=True, null=True, verbose_name='Link TheMembers')),
                ('asaas_product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Produto ASAAS')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professor', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('lessons_count', models.IntegerField(default=0, verbose_name='Número de Aulas')),
                ('duration', models.CharField(max_length=50, verbose_name='Duração')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('topics', models.TextField(blank=True, verbose_name='Tópicos')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('video_url', models.URLField(verbose_name='URL do Vídeo')),
                ('duration', models.CharField(max_length=50, verbose_name='Duração')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_free', models.BooleanField(default=False, verbose_name='É Gratuita')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['order'],
            },
        ),
    ]
