# Generated by Django 4.2.21 on 2025-08-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='full_description',
        ),
    ]
