# Generated by Django 4.2.21 on 2025-08-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detailed_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada'),
        ),
        migrations.AddField(
            model_name='course',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='courses/preview/', verbose_name='Imagem de Preview'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do Vídeo de Apresentação'),
        ),
    ]
