# Generated by Django 4.2.21 on 2025-08-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_detailed_description_course_image_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo do Curso'),
        ),
    ]
