# Generated by Django 4.2.21 on 2025-08-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_preview',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Imagem de Preview'),
        ),
    ]
