# Generated by Django 4.2.21 on 2025-08-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_image_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Mais Vendido'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Completo'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Novo'),
        ),
    ]
