# Generated by Django 4.2.21 on 2025-08-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('position', models.CharField(max_length=200, verbose_name='Cargo')),
                ('location', models.CharField(max_length=200, verbose_name='Localização')),
                ('result', models.CharField(max_length=200, verbose_name='Resultado')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Avaliação')),
                ('testimonial', models.TextField(verbose_name='Depoimento')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Imagem')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('status', models.CharField(choices=[('approved', 'Aprovado'), ('pending', 'Pendente'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
