# Generated by Django 4.2.21 on 2025-08-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(verbose_name='Avaliação'),
        ),
    ]
